name: legalai # Proje adınızı buraya yazın (küçük harf, boşluksuz)
description: "AI Lawyer Advisor MVP"
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Örnek bir SDK kısıtlaması, projenize göre ayarlayın

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3 # Keep versions updated
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.5.1 # Keep versions updated
  supabase_flutter: ^2.3.4 # Keep versions updated
  http: ^1.2.1 # Keep versions updated
  pdf: ^3.10.8 # Keep versions updated
  path_provider: ^2.1.3 # Keep versions updated
  open_filex: ^4.4.0 # Keep versions updated
  share_plus: ^11.0.0 # Upgrade share_plus
  json_annotation: ^4.9.0 # Keep versions updated
  # Add other dependencies below if needed
  cupertino_icons: ^1.0.6 # Example: Add if using Cupertino icons
  intl: ^0.19.0 # For date/time formatting
  flutter_dotenv: ^5.1.0 # Add dotenv package
  url_launcher: ^6.2.6
  card_swiper: ^3.0.1 # For document swiping functionality
  cached_network_image: ^3.4.0
  riverpod_annotation: ^2.3.3
  uuid: ^4.3.3 # Benzersiz ID
  flutter_pdfview: ^1.4.0+1 # Add flutter_pdfview
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_markdown: ^0.7.1
  google_fonts: ^6.1.0 # Fontları ekle
  file_picker: ^8.0.3 # Add file_picker
  google_mlkit_text_recognition: ^0.11.0 # Google ML Kit Text Recognition
  image_picker: ^1.0.7 # Kamera ve galeri erişimi için
  camera: ^0.10.5+9 # Kamera erişimi için
  syncfusion_flutter_pdfviewer: ^29.1.38
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1 # Keep versions updated
  build_runner: ^2.4.9 # Keep versions updated
  json_serializable: ^6.8.0 # Keep versions updated
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  freezed: ^2.3.2 # If using freezed

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/templates/ # Şablon JSON dosyalarını içeren klasör - Kaldırıldı
    - assets/images/ # A4 kağıdı gibi görselleri içeren klasör
    - .env
    - assets/logo.png # Logo eklendi
    - assets/dilekçe.jpg # Dilekçe örneği eklendi
    - assets/fonts/Roboto-Regular.ttf # Add Roboto font for Turkish character support
    # - assets/tessdata/ # Remove tessdata path
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages 